### ISSUE TITLE
How insert years 

### ISSUE THREAD

**Issue by luizaprestes** [flr/doc#8]
How can I put years not sequential when constructing the FLQuant matrix? I have data from the years 1978 to 1985, after 1993 to 1997 and 2008 to 2011 and I can not build the matrix considering years not sequences.
Thank you for your help

**Comment by iagomosqueira** [comment]
You can give a non-consecutive sequence as `dimnames$year` by passing your own vector, for example

```
x <- FLQuant(1, dimnames=list(age=1:3, year=c(1980, 1982)))
```

A good option is usually to keep all years but have the missing data as NA, for example by creatin g an object with the whole sequence and then assigning the values to those years for which there is data

```
x <- FLQuant(NA, dimnames=list(age=1:3, year=c(1980:1982)))

x[, '1980'] <- rnorm(3)
x[, '1982'] <- rnorm(3)
```

You could also create the object with only the data years, passing rhe matrix or vector of data instead of  1

```
x <- FLQuant(1, dimnames=list(age=1:3, year=c(1980, 1982)))
```

and then extend it using `window` even with the existing start and end year. New years will be created to complete the sequence but will be filled with `NA`

```
window(x, start=1980, end=1982)
An object of class "FLQuant"
, , unit = unique, season = all, area = unique

    year
age  1980 1981 1982
  1   1   NA    1  
  2   1   NA    1  
  3   1   NA    1  

units:  NA 
```
